version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:6.1.1  # Exemple de version spécifique
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka1
    depends_on:
      - zookeeper
    volumes:
      - kafka-data1:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    ports:
      - "29092:29092"

  kafka2:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka2
    depends_on:
      - zookeeper
    volumes:
      - kafka-data2:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    ports:
      - "29093:29093"

  kafka3:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka3
    depends_on:
      - zookeeper
    volumes:
      - kafka-data3:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    ports:
      - "29094:29094"

  cmak:
    image: hlebalbau/kafka-manager:latest
    container_name: cmak
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3

  kafka-monitor:
    image: solsson/kafka-prometheus-monitoring@sha256:75d5c3a1acc9fd04e26a537019a9553b58f5de297ef354523b3787d2a04bdec2
    container_name: kafka-monitor
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8080:8080"
    environment:
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-monitor -Dcom.sun.management.jmxremote.rmi.port=9999"
      PROMETHEUS_JMX_EXPORTER_PORT: "5556"
      KAFKA_BROKERS: "kafka1:29092,kafka2:29093,kafka3:29094"

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data1:
  kafka-data2:
  kafka-data3:
